services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: victor_user
      POSTGRES_PASSWORD: victor_password
      POSTGRES_DB: tarot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tarot-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    ## environment:
    ##  - DATABASE_URL=postgresql://postgres:postgres@db:5432/tarot

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: tarot-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: