services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: victor_user
      POSTGRES_PASSWORD: victor_password
      POSTGRES_DB: tarot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U victor_user -d tarot_db -h localhost"]
      interval: 2s
      timeout: 2s
      retries: 25

  backend:
    build:
      context: ./backend
    container_name: tarot-backend
    volumes:
      - ./backend:/app
      - /app/.venv # Avoid linking local .venv
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql+psycopg2://victor_user:victor_password@db:5432/tarot_db

  migrate:
    build:
      context: ./backend
    container_name: tarot-migrate
    command: uv run alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/.venv # Avoid linking local .venv
    environment:
      - DATABASE_URL=postgresql+psycopg2://victor_user:victor_password@db:5432/tarot_db

  frontend:
    build:
      context: ./frontend
    container_name: tarot-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Avoid linking local modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
