// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddPlayerApiPlayersPostData, AddPlayerApiPlayersPostErrors, AddPlayerApiPlayersPostResponses, CreateGameSessionApiGameSessionsPostData, CreateGameSessionApiGameSessionsPostErrors, CreateGameSessionApiGameSessionsPostResponses, DeleteGameSessionApiGameSessionsSessionIdDeleteData, DeleteGameSessionApiGameSessionsSessionIdDeleteErrors, DeleteGameSessionApiGameSessionsSessionIdDeleteResponses, GetGameSessionApiGameSessionsSessionIdGetData, GetGameSessionApiGameSessionsSessionIdGetErrors, GetGameSessionApiGameSessionsSessionIdGetResponses, GetSessionsWithScoresApiGameSessionsGetData, GetSessionsWithScoresApiGameSessionsGetErrors, GetSessionsWithScoresApiGameSessionsGetResponses, ListPartyResultsApiPartyResultsGetData, ListPartyResultsApiPartyResultsGetResponses, ListPlayersApiPlayersGetData, ListPlayersApiPlayersGetResponses, SubmitPartyResultApiPartyResultsPostData, SubmitPartyResultApiPartyResultsPostErrors, SubmitPartyResultApiPartyResultsPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Party Results
 */
export const listPartyResultsApiPartyResultsGet = <ThrowOnError extends boolean = false>(options?: Options<ListPartyResultsApiPartyResultsGetData, ThrowOnError>) => (options?.client ?? client).get<ListPartyResultsApiPartyResultsGetResponses, unknown, ThrowOnError>({ url: '/api/party-results/', ...options });

/**
 * Submit Party Result
 */
export const submitPartyResultApiPartyResultsPost = <ThrowOnError extends boolean = false>(options: Options<SubmitPartyResultApiPartyResultsPostData, ThrowOnError>) => (options.client ?? client).post<SubmitPartyResultApiPartyResultsPostResponses, SubmitPartyResultApiPartyResultsPostErrors, ThrowOnError>({
    url: '/api/party-results/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Players
 */
export const listPlayersApiPlayersGet = <ThrowOnError extends boolean = false>(options?: Options<ListPlayersApiPlayersGetData, ThrowOnError>) => (options?.client ?? client).get<ListPlayersApiPlayersGetResponses, unknown, ThrowOnError>({ url: '/api/players/', ...options });

/**
 * Add Player
 */
export const addPlayerApiPlayersPost = <ThrowOnError extends boolean = false>(options: Options<AddPlayerApiPlayersPostData, ThrowOnError>) => (options.client ?? client).post<AddPlayerApiPlayersPostResponses, AddPlayerApiPlayersPostErrors, ThrowOnError>({
    url: '/api/players/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Sessions With Scores
 */
export const getSessionsWithScoresApiGameSessionsGet = <ThrowOnError extends boolean = false>(options?: Options<GetSessionsWithScoresApiGameSessionsGetData, ThrowOnError>) => (options?.client ?? client).get<GetSessionsWithScoresApiGameSessionsGetResponses, GetSessionsWithScoresApiGameSessionsGetErrors, ThrowOnError>({ url: '/api/game-sessions/', ...options });

/**
 * Create Game Session
 */
export const createGameSessionApiGameSessionsPost = <ThrowOnError extends boolean = false>(options: Options<CreateGameSessionApiGameSessionsPostData, ThrowOnError>) => (options.client ?? client).post<CreateGameSessionApiGameSessionsPostResponses, CreateGameSessionApiGameSessionsPostErrors, ThrowOnError>({
    url: '/api/game-sessions/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Game Session
 */
export const deleteGameSessionApiGameSessionsSessionIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteGameSessionApiGameSessionsSessionIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteGameSessionApiGameSessionsSessionIdDeleteResponses, DeleteGameSessionApiGameSessionsSessionIdDeleteErrors, ThrowOnError>({ url: '/api/game-sessions/{session_id}', ...options });

/**
 * Get Game Session
 */
export const getGameSessionApiGameSessionsSessionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetGameSessionApiGameSessionsSessionIdGetData, ThrowOnError>) => (options.client ?? client).get<GetGameSessionApiGameSessionsSessionIdGetResponses, GetGameSessionApiGameSessionsSessionIdGetErrors, ThrowOnError>({ url: '/api/game-sessions/{session_id}', ...options });
