// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ChlemType
 */
export type ChlemType = 'Annoncé et passé' | 'Non annoncé et passé' | 'Annoncé et chuté';

/**
 * ContractType
 */
export type ContractType = 'Petite' | 'Garde' | 'Garde sans' | 'Garde contre';

/**
 * GameSessionCreate
 */
export type GameSessionCreate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Player 1 Id
     */
    player_1_id: number;
    /**
     * Player 2 Id
     */
    player_2_id: number;
    /**
     * Player 3 Id
     */
    player_3_id: number;
    /**
     * Player 4 Id
     */
    player_4_id: number;
    /**
     * Player 5 Id
     */
    player_5_id?: number | null;
};

/**
 * GameSessionDetail
 */
export type GameSessionDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string | null;
    /**
     * Create Timestamp
     */
    create_timestamp: string;
    /**
     * Players
     */
    players: Array<PlayerRead>;
    /**
     * Party Results
     */
    party_results: Array<PartyResultSummary>;
    /**
     * Scores
     */
    scores: Array<PlayerScoreSummary>;
};

/**
 * GameSessionRead
 */
export type GameSessionRead = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Player 1 Id
     */
    player_1_id: number;
    /**
     * Player 2 Id
     */
    player_2_id: number;
    /**
     * Player 3 Id
     */
    player_3_id: number;
    /**
     * Player 4 Id
     */
    player_4_id: number;
    /**
     * Player 5 Id
     */
    player_5_id?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Create Timestamp
     */
    create_timestamp: string;
};

/**
 * GameSessionSummary
 */
export type GameSessionSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string | null;
    /**
     * Create Timestamp
     */
    create_timestamp: string;
    /**
     * Nb Parties
     */
    nb_parties: number;
    /**
     * Scores
     */
    scores: Array<PlayerScoreSummary>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PartyResultCreate
 */
export type PartyResultCreate = {
    /**
     * Taker Id
     */
    taker_id: number;
    /**
     * Game Session Id
     */
    game_session_id: number;
    /**
     * Called Player Id
     */
    called_player_id: number;
    contract: ContractType;
    /**
     * Oudlers
     */
    oudlers: number;
    /**
     * Points
     */
    points: number;
    /**
     * Petit Au Bout Player Id
     */
    petit_au_bout_player_id?: number | null;
    /**
     * Petit Au Bout Won
     */
    petit_au_bout_won?: boolean | null;
    /**
     * Poignee Simple Players Ids
     */
    poignee_simple_players_ids: Array<number>;
    /**
     * Poignee Double Players Ids
     */
    poignee_double_players_ids: Array<number>;
    /**
     * Poignee Triple Players Ids
     */
    poignee_triple_players_ids: Array<number>;
    /**
     * Misere Tete Players Ids
     */
    misere_tete_players_ids: Array<number>;
    /**
     * Misere Atout Players Ids
     */
    misere_atout_players_ids: Array<number>;
    chlem?: ChlemType | null;
};

/**
 * PartyResultRead
 */
export type PartyResultRead = {
    /**
     * Taker Id
     */
    taker_id: number;
    /**
     * Game Session Id
     */
    game_session_id: number;
    /**
     * Called Player Id
     */
    called_player_id: number;
    contract: ContractType;
    /**
     * Oudlers
     */
    oudlers: number;
    /**
     * Points
     */
    points: number;
    /**
     * Petit Au Bout Player Id
     */
    petit_au_bout_player_id?: number | null;
    /**
     * Petit Au Bout Won
     */
    petit_au_bout_won?: boolean | null;
    /**
     * Poignee Simple Players Ids
     */
    poignee_simple_players_ids: Array<number>;
    /**
     * Poignee Double Players Ids
     */
    poignee_double_players_ids: Array<number>;
    /**
     * Poignee Triple Players Ids
     */
    poignee_triple_players_ids: Array<number>;
    /**
     * Misere Tete Players Ids
     */
    misere_tete_players_ids: Array<number>;
    /**
     * Misere Atout Players Ids
     */
    misere_atout_players_ids: Array<number>;
    chlem?: ChlemType | null;
    /**
     * Id
     */
    id: number;
    /**
     * Create Timestamp
     */
    create_timestamp: string;
};

/**
 * PartyResultSummary
 */
export type PartyResultSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Taker
     */
    taker: string;
    /**
     * Called
     */
    called: string;
    /**
     * Points
     */
    points: number;
    /**
     * Create Timestamp
     */
    create_timestamp: string;
    /**
     * Scores
     */
    scores: Array<PlayerScoreSummary>;
};

/**
 * PlayerCreate
 */
export type PlayerCreate = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * PlayerRead
 */
export type PlayerRead = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Id
     */
    id: number;
    /**
     * Visible
     */
    visible: boolean;
};

/**
 * PlayerScoreSummary
 */
export type PlayerScoreSummary = {
    /**
     * Player Id
     */
    player_id: number;
    /**
     * Score
     */
    score: number;
    /**
     * Player
     */
    player: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListPartyResultsApiPartyResultsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/party-results/';
};

export type ListPartyResultsApiPartyResultsGetResponses = {
    /**
     * Response List Party Results Api Party Results  Get
     *
     * Successful Response
     */
    200: Array<PartyResultRead>;
};

export type ListPartyResultsApiPartyResultsGetResponse = ListPartyResultsApiPartyResultsGetResponses[keyof ListPartyResultsApiPartyResultsGetResponses];

export type SubmitPartyResultApiPartyResultsPostData = {
    body: PartyResultCreate;
    path?: never;
    query?: never;
    url: '/api/party-results/';
};

export type SubmitPartyResultApiPartyResultsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitPartyResultApiPartyResultsPostError = SubmitPartyResultApiPartyResultsPostErrors[keyof SubmitPartyResultApiPartyResultsPostErrors];

export type SubmitPartyResultApiPartyResultsPostResponses = {
    /**
     * Successful Response
     */
    200: PartyResultRead;
};

export type SubmitPartyResultApiPartyResultsPostResponse = SubmitPartyResultApiPartyResultsPostResponses[keyof SubmitPartyResultApiPartyResultsPostResponses];

export type ListPlayersApiPlayersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/players/';
};

export type ListPlayersApiPlayersGetResponses = {
    /**
     * Response List Players Api Players  Get
     *
     * Successful Response
     */
    200: Array<PlayerRead>;
};

export type ListPlayersApiPlayersGetResponse = ListPlayersApiPlayersGetResponses[keyof ListPlayersApiPlayersGetResponses];

export type AddPlayerApiPlayersPostData = {
    body: PlayerCreate;
    path?: never;
    query?: never;
    url: '/api/players/';
};

export type AddPlayerApiPlayersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPlayerApiPlayersPostError = AddPlayerApiPlayersPostErrors[keyof AddPlayerApiPlayersPostErrors];

export type AddPlayerApiPlayersPostResponses = {
    /**
     * Successful Response
     */
    200: PlayerRead;
};

export type AddPlayerApiPlayersPostResponse = AddPlayerApiPlayersPostResponses[keyof AddPlayerApiPlayersPostResponses];

export type GetSessionsWithScoresApiGameSessionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/game-sessions/';
};

export type GetSessionsWithScoresApiGameSessionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSessionsWithScoresApiGameSessionsGetError = GetSessionsWithScoresApiGameSessionsGetErrors[keyof GetSessionsWithScoresApiGameSessionsGetErrors];

export type GetSessionsWithScoresApiGameSessionsGetResponses = {
    /**
     * Response Get Sessions With Scores Api Game Sessions  Get
     *
     * Successful Response
     */
    200: Array<GameSessionSummary>;
};

export type GetSessionsWithScoresApiGameSessionsGetResponse = GetSessionsWithScoresApiGameSessionsGetResponses[keyof GetSessionsWithScoresApiGameSessionsGetResponses];

export type CreateGameSessionApiGameSessionsPostData = {
    body: GameSessionCreate;
    path?: never;
    query?: never;
    url: '/api/game-sessions/';
};

export type CreateGameSessionApiGameSessionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGameSessionApiGameSessionsPostError = CreateGameSessionApiGameSessionsPostErrors[keyof CreateGameSessionApiGameSessionsPostErrors];

export type CreateGameSessionApiGameSessionsPostResponses = {
    /**
     * Successful Response
     */
    200: GameSessionRead;
};

export type CreateGameSessionApiGameSessionsPostResponse = CreateGameSessionApiGameSessionsPostResponses[keyof CreateGameSessionApiGameSessionsPostResponses];

export type DeleteGameSessionApiGameSessionsSessionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: number;
    };
    query?: never;
    url: '/api/game-sessions/{session_id}';
};

export type DeleteGameSessionApiGameSessionsSessionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGameSessionApiGameSessionsSessionIdDeleteError = DeleteGameSessionApiGameSessionsSessionIdDeleteErrors[keyof DeleteGameSessionApiGameSessionsSessionIdDeleteErrors];

export type DeleteGameSessionApiGameSessionsSessionIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGameSessionApiGameSessionsSessionIdDeleteResponse = DeleteGameSessionApiGameSessionsSessionIdDeleteResponses[keyof DeleteGameSessionApiGameSessionsSessionIdDeleteResponses];

export type GetGameSessionApiGameSessionsSessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: number;
    };
    query?: never;
    url: '/api/game-sessions/{session_id}';
};

export type GetGameSessionApiGameSessionsSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameSessionApiGameSessionsSessionIdGetError = GetGameSessionApiGameSessionsSessionIdGetErrors[keyof GetGameSessionApiGameSessionsSessionIdGetErrors];

export type GetGameSessionApiGameSessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: GameSessionDetail;
};

export type GetGameSessionApiGameSessionsSessionIdGetResponse = GetGameSessionApiGameSessionsSessionIdGetResponses[keyof GetGameSessionApiGameSessionsSessionIdGetResponses];
