"""add players ids to game session table

Revision ID: 00cfa1cfa120
Revises: 4343a2a093e3
Create Date: 2025-08-19 14:01:42.235496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cfa1cfa120'
down_revision: Union[str, Sequence[str], None] = '4343a2a093e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('player_1_id', sa.Integer(), nullable=False))
    op.add_column('game_sessions', sa.Column('player_2_id', sa.Integer(), nullable=False))
    op.add_column('game_sessions', sa.Column('player_3_id', sa.Integer(), nullable=False))
    op.add_column('game_sessions', sa.Column('player_4_id', sa.Integer(), nullable=False))
    op.add_column('game_sessions', sa.Column('player_5_id', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('nb_players', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'game_sessions', 'players', ['player_1_id'], ['id'])
    op.create_foreign_key(None, 'game_sessions', 'players', ['player_3_id'], ['id'])
    op.create_foreign_key(None, 'game_sessions', 'players', ['player_4_id'], ['id'])
    op.create_foreign_key(None, 'game_sessions', 'players', ['player_5_id'], ['id'])
    op.create_foreign_key(None, 'game_sessions', 'players', ['player_2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.drop_column('game_sessions', 'nb_players')
    op.drop_column('game_sessions', 'player_5_id')
    op.drop_column('game_sessions', 'player_4_id')
    op.drop_column('game_sessions', 'player_3_id')
    op.drop_column('game_sessions', 'player_2_id')
    op.drop_column('game_sessions', 'player_1_id')
    # ### end Alembic commands ###
