"""correct name called_player_id

Revision ID: 0e773508c4aa
Revises: c337db3125b8
Create Date: 2025-08-18 21:06:15.585054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e773508c4aa'
down_revision: Union[str, Sequence[str], None] = 'c337db3125b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('called_player_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('party_results_called_id_fkey'), 'party_results', type_='foreignkey')
    op.create_foreign_key(None, 'party_results', 'players', ['called_player_id'], ['id'])
    op.drop_column('party_results', 'called_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('called_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'party_results', type_='foreignkey')
    op.create_foreign_key(op.f('party_results_called_id_fkey'), 'party_results', 'players', ['called_id'], ['id'])
    op.drop_column('party_results', 'called_player_id')
    # ### end Alembic commands ###
