"""rename id colums

Revision ID: 113b8b42e21d
Revises: bb7a98aa93bc
Create Date: 2025-08-18 20:50:05.791155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '113b8b42e21d'
down_revision: Union[str, Sequence[str], None] = 'bb7a98aa93bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('taker_id', sa.Integer(), nullable=False))
    op.add_column('party_results', sa.Column('called_id', sa.Integer(), nullable=False))
    op.alter_column('party_results', 'petit',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('party_results', 'taker')
    op.drop_column('party_results', 'called')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('called', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('party_results', sa.Column('taker', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('party_results', 'petit',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('party_results', 'called_id')
    op.drop_column('party_results', 'taker_id')
    # ### end Alembic commands ###
