"""split miseres and poignees into different columns

Revision ID: 20eb703cd010
Revises: 4cd167019e62
Create Date: 2025-08-18 22:21:08.991974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20eb703cd010'
down_revision: Union[str, Sequence[str], None] = '4cd167019e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('poignee_simple_players_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
    op.add_column('party_results', sa.Column('poignee_double_players_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
    op.add_column('party_results', sa.Column('poignee_triple_players_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
    op.add_column('party_results', sa.Column('misere_tete_players_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
    op.add_column('party_results', sa.Column('misere_atout_players_ids', postgresql.ARRAY(sa.Integer()), nullable=False))
    op.drop_column('party_results', 'poignees')
    op.drop_column('party_results', 'miseres')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('miseres', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('party_results', sa.Column('poignees', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('party_results', 'misere_atout_players_ids')
    op.drop_column('party_results', 'misere_tete_players_ids')
    op.drop_column('party_results', 'poignee_triple_players_ids')
    op.drop_column('party_results', 'poignee_double_players_ids')
    op.drop_column('party_results', 'poignee_simple_players_ids')
    # ### end Alembic commands ###
