"""add timetstamp column

Revision ID: 4343a2a093e3
Revises: 3fafa4190e4f
Create Date: 2025-08-19 13:35:43.888525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4343a2a093e3'
down_revision: Union[str, Sequence[str], None] = '3fafa4190e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('create_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party_results', 'create_timestamp')
    # ### end Alembic commands ###
