"""add scores table

Revision ID: 458a6a0a0585
Revises: cac83489bdd8
Create Date: 2025-08-22 13:58:14.569193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458a6a0a0585'
down_revision: Union[str, Sequence[str], None] = 'cac83489bdd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_result_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_result_id'], ['party_results.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_scores_id'), 'party_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_party_scores_id'), table_name='party_scores')
    op.drop_table('party_scores')
    # ### end Alembic commands ###
