"""split petit au bout into two columns

Revision ID: 4cd167019e62
Revises: 0e773508c4aa
Create Date: 2025-08-18 21:42:16.396806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd167019e62'
down_revision: Union[str, Sequence[str], None] = '0e773508c4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('petit_au_bout_player_id', sa.Integer(), nullable=True))
    op.add_column('party_results', sa.Column('petit_au_bout_won', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'party_results', 'players', ['petit_au_bout_player_id'], ['id'])
    op.drop_column('party_results', 'petit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_results', sa.Column('petit', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'party_results', type_='foreignkey')
    op.drop_column('party_results', 'petit_au_bout_won')
    op.drop_column('party_results', 'petit_au_bout_player_id')
    # ### end Alembic commands ###
