"""add unique contrain on player table

Revision ID: 4f9b379af14e
Revises: 53ef2dc9c207
Create Date: 2025-08-13 20:41:39.100276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9b379af14e'
down_revision: Union[str, Sequence[str], None] = '53ef2dc9c207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_player_name', 'players', ['first_name', 'last_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_player_name', 'players', type_='unique')
    # ### end Alembic commands ###
