"""Create questionnaires table

Revision ID: 61adb3517ea4
Revises: 619d474ddd2f
Create Date: 2025-08-03 13:59:33.046343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61adb3517ea4"
down_revision: Union[str, Sequence[str], None] = "619d474ddd2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questionnaires_id"), table_name="questionnaires")
    op.drop_table("questionnaires")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questionnaires",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "feedback", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("questionnaires_pkey")),
    )
    op.create_index(
        op.f("ix_questionnaires_id"), "questionnaires", ["id"], unique=False
    )
    # ### end Alembic commands ###
