"""add foreign keys

Revision ID: c337db3125b8
Revises: 113b8b42e21d
Create Date: 2025-08-18 20:56:31.575512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c337db3125b8'
down_revision: Union[str, Sequence[str], None] = '113b8b42e21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'party_results', 'players', ['called_id'], ['id'])
    op.create_foreign_key(None, 'party_results', 'players', ['taker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'party_results', type_='foreignkey')
    op.drop_constraint(None, 'party_results', type_='foreignkey')
    # ### end Alembic commands ###
